add changeset and test
spidasoftware/schema pull request #407
Opened 2022-10-18 12:45 UTC by spidaDillon

2022-10-18 13:05 UTC, jasongarrett requested changes

2022-10-18 13:05 UTC, jasongarrett commented on src/main/groovy/com/spidasoftware/schema/conversion/changeset/v9/ExtremeWindLoadCaseChangeset.groovy
> +        if (projectJSON.containsKey("leads")) {
I think you shouldn't need this since you implemented revertDesign.

2022-10-18 15:03 UTC, samwise4 approved these changes

2022-10-31 13:45 UTC, jasongarrett commented on src/main/groovy/com/spidasoftware/schema/conversion/changeset/client/AbstractClientDataChangeSet.groovy
> +        return true
should only return true if anything was changed

2022-10-31 13:46 UTC, jasongarrett commented on src/main/groovy/com/spidasoftware/schema/conversion/changeset/client/AbstractClientDataChangeSet.groovy
> +        return true
should only return true if anything was changed

2022-10-31 13:46 UTC, jasongarrett commented on src/main/groovy/com/spidasoftware/schema/conversion/changeset/v9/EnvironmentClientDataChangeset.groovy
> +		return true
should only return true if anything was changed

2022-10-31 13:47 UTC, jasongarrett commented on src/main/groovy/com/spidasoftware/schema/conversion/changeset/v9/EnvironmentClientDataChangeset.groovy
> +		return true
should only return true if anything was changed

2022-10-31 14:13 UTC, jasongarrett requested changes

2022-10-31 14:45 UTC, jasongarrett approved these changes

2022-10-31 15:31 UTC, merged